### ISSUE TITLE
Can I help ?

### ISSUE THREAD

**Issue by AlixANNERAUD** [dynamium/lv_cxx_bindgen#4]
Hey, I would like to know if I can help ? I started previous summer a binding tool in python, but since then classes started again and I didn't have much time to make progress on them. Doing it in rust ultimately seems relevant to me because the lack of typing in python drives me crazy.

**Comment by ggoraa** [comment]
Hi!

Yea, you definitely can! The only problem for now is that because this generator is basically in pre-alpha stage, it will have shit loads of changes all the time, it's not stable (in terms of code change) at all, it will be a nightmare to try to contribute something to the main algorithm.
But, when some time passes and it starts to be more, idk, "mature" or smth (the code doesn't get rewritten each commit basically), and if you know Rust well enough, you can safely start contributing :)

I'm right now in the middle of figuring out how to structure the HL-AST (High-Level Abstract Syntax Tree) generator (step that sits between API map parsing and code generation), and when I will finish that, you can probably do something with that part of the program
Wait, I have an idea, when I finish the HL-AST generator architecture, I will do the namespace/class generation with it, but my plan was to also generate enums, structs, etc., so I think I have an exact thing that you can do :)

**Comment by AlixANNERAUD** [comment]
Sure, that sounds good to me. Let me know when you complete HL-AST (either by replying to this issue or assigning one to me). I'm quite good in both C++ and Rust, so feel free to reach out if you require assistance with HL-AST. Good luck !

**Comment by ggoraa** [comment]
@AlixANNERAUD Hi again!

So, I finished the architecture, and code for function processing and namespace generation. Can I ask you to do struct/enum processing, and if you have time for that, class generation?

**Comment by AlixANNERAUD** [comment]
"Okay, great! I'll get started right away. However, on which branch should I base mine to get started? Is master up to date ? Yes, of course, here is my matrix account (self-hosted) : @alix_anneraud:insa.lol.
